import type { Metadata } from "next";
import { Geist, Geist_Mono, Red_Hat_Display } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { useColorMode } from "@/components/ui/color-mode";

const geistSans = Red_Hat_Display({
  variable: "--font-red-hat-display",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gamr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className={`min-h-full flex flex-col bg-[#151515] ${"dark:bg-[#151515] dark:text-white"}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
